version: '3.7'
services:
      postgres:
        build: .
        image: postgres:10.5
        container_name: questionsandanswers
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./mySchema.sql:/docker-entrypoint-initdb.d/mySchema.sql